# Generated by Django 4.2.6 on 2023-11-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='po',
            old_name='cust',
            new_name='cust_id',
        ),
    ]
