# Generated by Django 4.2.6 on 2023-11-02 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_cust_po_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otwdc',
            name='po_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
